services:
  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "4080:1080"
      - "4025:1025"
  mysqldb:
    image: mysql:8.0.37
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=learn_n_play
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: