spring:
  application:
    name: learn-n-play
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3307/learn_n_play}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:4026}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:false}
          starttls:
            enable: ${MAIL_TLS:false}

app:
  path: ${APP_PATH:http://localhost:8080}
  ui-path: ${APP_UI_PATH:http://localhost:5173}
  security:
    jwt:
      access:
        secret: ${JWT_ACCESS_SECRET:JWT_ACCESS_TOKEN_SECRET}
        expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:86400000}